spring.application.name=uptime-monitor
spring.datasource.url=jdbc:postgresql://localhost:5432/db_uptime_monitor
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

api.security.token.secret=${JWT_SECRET:07062009}